### API SIGN-UP
POST http://localhost:8080/api/sign-up
Content-Type: application/json

{
  "name" : "abcde",
  "email": "abcde@abcde.com",
  "password": "abcde",
  "birthday": "2023-03-29"
}


### API LOGIN
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "abcde@abcde.com",
  "password": "abcde"
}



### CREATE Task
POST http://localhost:8080/api/schedules/tasks?userId=5
Content-Type: application/json
Cookie: {{cookie}}

{
  "title": "운동가기",
  "description": "벤치프레스",
  "taskAt": "2023-03-16T12:00:00"
}



### CREATE Event
POST http://localhost:8080/api/schedules/events?userId=5
Content-Type: application/json
Cookie: {{cookie}}

{
  "title": "여행가자",
  "description": "강원도로",
  "startAt": "2023-03-16T11:00:00",
  "endAt": "2023-03-18T11:00:00",
  "attendeeIds": [2]
}



### CREATE Notification
POST http://localhost:8080/api/schedules/notifications?userId=5
Content-Type: application/json
Cookie: {{cookie}}

{
  "title": "아침 수영",
  "notifyAt": "2023-03-16T07:00:00",
  "repeatInfo": {
    "interval": {
      "intervalValue": 2,
      "timeUnit": "DAY"
    },
    "times": 5
  }
}


### QUERY BY DAY
GET http://localhost:8080/api/schedules/day?userId=5&date=2023-03-16

### QUERY BY WEEK
GET http://localhost:8080/api/schedules/week?userId=5&startOfWeek=2023-03-16

### QUERY BY MONTH
GET http://localhost:8080/api/schedules/month?userId=5&yearMonth=2023-03